version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5173"
    environment:
        - VITE_API_HOST=${VITE_API_HOST}
    volumes:
      - .:/app
      - /app/node_modules
